# Generated by Django 5.0.4 on 2024-05-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalprice",
            old_name="stock",
            new_name="symbol",
        ),
    ]
