# Generated by Django 5.0.4 on 2024-05-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_rename_stock_historicalprice_symbol"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="historicalprice",
            unique_together={("symbol", "date")},
        ),
    ]
